#pragma once

#include "Elements/PlayerState_StandBy.h"
#include "Elements/PlayerState_Idle.h"
#include "Elements/PlayerState_MoveEach.h"
#include "Elements/PlayerState_MoveBoth.h"
#include "Elements/PlayerState_Jump.h"
#include "Elements/Hold/Wall/PlayerState_HoldBegin.h"
#include "Elements/Hold/Wall/PlayerState_HoldSwim.h"
#include "Elements/Hold/Wall/PlayerState_HoldFull.h"
#include "Elements/Hold/Air/PlayerState_HoldAirBegin.h"
#include "Elements/Hold/Air/PlayerState_HoldAirSwim.h"
#include "Elements/Hold/Air/PlayerState_HoldAirFull.h"
#include "Elements/Hold/PlayerState_HoldBoth.h"
#include "Elements/PlayerState_Attack.h"
#include "Elements/PlayerState_Freeze.h"
#include "Elements/PlayerState_EventTime.h"
#include "Elements/PlayerState_LeanBack.h"
