#ifndef BOSS_ANIMATION_NUMBER_H_
#define BOSS_ANIMATION_NUMBER_H_

enum {
	WAIT_NUMBER = 0,
	WAIT_TURN_NUMBER = 1,
	JUMP_UP_NUMBER = 2,
	JUMP_DOWN_NUMBER = 3,
	WALLATTACK_DASH_NUMBER = 4,
	WALLATTACK_DASHJUMP_NUMBER = 5,
	WALLATTACK_DASHJUMP_STOP_NUMBER = 6,
	BREATH_DYSFUNCTION_NUMBER = 9,
	PIYO_NUMBER = 11,
	DAMAGE_NUMBER = 12,
	DAMAGE_BOKO_NUMBER = 13,
	DEATH_NUMBER = 14
};

#endif
