#ifndef BOSS_ANIMATION_NUMBER_H_
#define BOSS_ANIMATION_NUMBER_H_

enum class BossAnimationNumber{
	WAIT_NUMBER,
	WAIT_TURN_NUMBER,
	JUMP_UP_NUMBER,
	JUMP_DOWN_NUMBER,
	WALLATTACK_DASH_NUMBER,
	WALLATTACK_DASHJUMP_NUMBER,
	WALLATTACK_DASHJUMP_STOP_NUMBER,
	BREATH_NUMBER,
	BREATH_TURN_NUMBER,
	BREATH_DYSFUNCTION_NUMBER,
	BREATH_LESS_NUMBER,
	PIYO_NUMBER,
	DAMAGE_NUMBER,
	DAMAGE_BOKO_NUMBER,
	DEATH_NUMBER,
};

#endif
