#ifndef IMPORT_ANIMATION_NUMBER_H_
#define IMPORT_ANIMATION_NUMBER_H_

// アニメーション番号
enum {
	WAIT_NUMBER = 0,
	RUN_NUMBER = 1,
	ADHERE_NUMBER = 2,
	DEAD_NUMBER = 3,
	WING_ATTACK_NUMBER = 4,
	WALL_ATTACK_NUMBER = 5,
	PIYORI_NUMBER = 6
};

#endif